- name: Add repository from PPA and install its signing key
  apt_repository: repo=ppa:chris-lea/redis-server update_cache=yes

- name: Install Redis Server
  apt: name=redis-server state=latest

- name: Update configuration file
  template: src=redis.conf.j2 dest=/etc/redis/redis.conf owner=root group=root mode=0644
  notify: restart redis